/**
 * Accountable forms (board certificates) from the PRC RAAF workbook, Jan 2025 - Feb 2026.
 * Spelling is normalised: the workbook has "AGIRCULTURAL AND BIOSYSTEM" and uses both
 * "CHEMICAL TECH" and "CHEMICAL TECHNICIAN"; footnote markers (***) are dropped.
 * Seeded into the form_catalog table; administrators can extend it from the database.
 */
export const FORM_CATALOG: string[] = [
  "AERONAUTICAL ENGINEER", "AGRICULTURAL AND BIOSYSTEMS ENGINEER", "AGRICULTURIST", "ARCHITECT",
  "CERTIFIED PLANT MECHANIC", "CERTIFIED PUBLIC ACCOUNTANT", "CHEMICAL ENGINEER", "CHEMICAL TECHNICIAN",
  "CHEMIST", "CIVIL ENGINEER", "CRIMINOLOGIST", "DENTIST", "ELECTRONICS ENGINEER", "ELECTRONICS TECHNICIAN",
  "ENVIRONMENTAL PLANNER", "FISHERIES PROFESSIONAL", "FORESTER", "GEODETIC ENGINEER", "GUIDANCE COUNSELOR",
  "INTERIOR DESIGNER", "LANDSCAPE ARCHITECT", "LIBRARIAN", "MASTER PLUMBER", "MECHANICAL ENGINEER",
  "MEDICAL LABORATORY TECHNICIAN", "MEDICAL TECHNOLOGIST", "METALLURGICAL ENGINEER", "MIDWIFE", "MINING ENGINEER",
  "NURSE", "NUTRITIONIST DIETICIAN", "OCCUPATIONAL THERAPIST", "OPTOMETRIST", "PHARMACIST", "PHYSICAL THERAPIST",
  "PHYSICIAN", "PROFESSIONAL ELECTRICAL ENGINEER", "PROFESSIONAL ELECTRONICS ENGINEER",
  "PROFESSIONAL FOOD TECHNOLOGIST", "PROFESSIONAL MECHANICAL ENGINEER", "PROFESSIONAL TEACHERS - ELEMENTARY",
  "PROFESSIONAL TEACHERS - SECONDARY", "PSYCHOLOGIST", "PSYCHOMETRICIAN", "RADIOLOGIC TECHNOLOGIST",
  "REAL ESTATE APPRAISER", "REAL ESTATE BROKER", "REGISTERED ELECTRICAL ENGINEER", "REGISTERED MASTER ELECTRICIAN",
  "RESPIRATORY THERAPIST", "SANITARY ENGINEER", "SOCIAL WORKER", "SPEECH LANGUAGE PATHOLOGIST", "VETERINARIAN",
  "X-RAY TECHNOLOGIST",
];
